version: "2"
run:
  timeout: 5m
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - musttag
    - nlreturn
    - noctx
    - noinlineerr
    - paralleltest
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 11
    gosmopolitan:
      allow-time-local: true
    varnamelen:
      max-distance: 15
      ignore-decls:
        - db *bbolt.DB
        - w *httptest.ResponseRecorder
        - w http.ResponseWriter
        - r *http.Request
  exclusions:
    generated: lax
    paths:
      - _test\.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - golines
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  unique-by-line: false
